// web/src/pages/file-manager/file-manager-page.tsx
import { useState, useEffect, useCallback, useMemo } from 'react';
import { useSearchParams } from 'react-router';
import { useQueryClient } from '@tanstack/react-query';
import { usePageTitle } from '@/hooks/use-page-title';
import { useFileManagerStore } from '@/stores/file-manager.store';
import { useFolder, useFileDetail } from '@/api/file-manager.api';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { FileDetailSheet } from '@/components/file-detail-sheet';
import { Badge } from '@/components/ui/badge';
import { Spinner } from '@/components/ui/spinner';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { cn, formatFileSize, formatSelectionCount, getFileExtension, getFileTypeBadgeColor } from '@/lib/utils';
import {
  Folder,
  FileText,
  ChevronRight,
  CheckSquare,
  RotateCcw,
  AlertCircle,
  FolderOpen,
} from 'lucide-react';
import type { FileItem, StorageContext } from '@/api/types';
import { CopyToBar } from '@/components/copy-to-bar';
import { type CopyProviderId } from '@/lib/providers';
import { CopyToDropboxDialog } from './copy-to-dropbox-dialog';
import { CopyToGoogleDriveDialog } from './copy-to-google-drive-dialog';
import { CopyToGcsDialog } from './copy-to-gcs-dialog';
import { CopyToGooglePhotosDialog } from './copy-to-google-photos-dialog';
import { CopyToPcloudDialog } from './copy-to-pcloud-dialog';

// ─── Helpers ───

function readContext(): StorageContext {
  try {
    const raw = sessionStorage.getItem('fm_context');
    if (raw) return JSON.parse(raw) as StorageContext;
  } catch {
    /* ignore */
  }
  return { provider: 'azure' };
}

function buildBreadcrumbs(context: StorageContext, pathSegments: string[]) {
  const crumbs: { label: string; path: string | null }[] = [];

  if (context.account) {
    crumbs.push({ label: context.account, path: '' });
  }
  if (context.container) {
    crumbs.push({ label: context.container, path: '' });
  }
  if (context.bucket) {
    crumbs.push({ label: context.bucket, path: '' });
  }

  let accumulated = '';
  for (const segment of pathSegments) {
    accumulated = accumulated ? `${accumulated}/${segment}` : segment;
    crumbs.push({ label: segment, path: accumulated });
  }

  return crumbs;
}

// ─── Component ───

export function Component() {
  usePageTitle('File Manager');

  const queryClient = useQueryClient();
  const [searchParams, setSearchParams] = useSearchParams();

  // Store state
  const {
    context,
    currentPath,
    items,
    currentFile,
    showDetail,
    error,
    selectionMode,
    selectedFiles,
    selectedFolders,
    setContext,
    setItems,
    setError,
    setCurrentFile,
    closeDetail,
    toggleSelectionMode,
    toggleFileSelection,
    toggleFolderSelection,
    clearSelection,
  } = useFileManagerStore();

  // Detail file path for query
  const [detailPath, setDetailPath] = useState<string | null>(null);

  // Copy dialog state
  const [activeDialog, setActiveDialog] = useState<CopyProviderId | null>(null);

  // Read context from session storage on mount
  useEffect(() => {
    const ctx = readContext();
    setContext(ctx);
  }, [setContext]);

  // Current path from URL
  const pathParam = searchParams.get('path');

  // Data fetching
  const {
    data: folderData,
    isLoading,
    isError,
    error: queryError,
    refetch,
  } = useFolder(pathParam, context, !!context.provider);

  const {
    data: fileDetailData,
  } = useFileDetail(detailPath, context, !!detailPath);

  // Sync folder data to store
  useEffect(() => {
    if (folderData) {
      setItems(folderData, pathParam);
    }
  }, [folderData, pathParam, setItems]);

  // Sync query error to store
  useEffect(() => {
    if (isError && queryError) {
      const msg = queryError instanceof Error ? queryError.message : 'Failed to load files';
      setError(msg);
    }
  }, [isError, queryError, setError]);

  // Sync file detail data to store
  useEffect(() => {
    if (fileDetailData) {
      setCurrentFile(fileDetailData);
    }
  }, [fileDetailData, setCurrentFile]);

  // ─── Handlers ───

  const handleNavigateToFolder = useCallback(
    (folderPath: string) => {
      setSearchParams({ path: folderPath });
    },
    [setSearchParams],
  );

  const handleBreadcrumbClick = useCallback(
    (path: string | null) => {
      if (path === null) return;
      if (path === '') {
        setSearchParams({});
      } else {
        setSearchParams({ path });
      }
    },
    [setSearchParams],
  );

  const handleFileClick = useCallback((file: FileItem) => {
    setDetailPath(file.itemPath);
  }, []);

  const handleRefresh = useCallback(() => {
    queryClient.invalidateQueries({ queryKey: ['files', 'folder'] });
    refetch();
  }, [queryClient, refetch]);

  const handleCloseDetail = useCallback(() => {
    closeDetail();
    setDetailPath(null);
  }, [closeDetail]);

  // ─── Derived state ───

  const folders = items?.filter((i) => i.isFolder) ?? [];
  const files = items?.filter((i) => !i.isFolder) ?? [];
  const breadcrumbs = buildBreadcrumbs(context, currentPath);
  const totalSelected = selectedFiles.size + selectedFolders.size;
  const providerLabel = context.provider === 'azure' ? 'Azure Blob' : 'Google Cloud';

  const selectedFileObjects = useMemo(
    () =>
      (items ?? []).filter(
        (i) => selectedFiles.has(i.itemPath) || selectedFolders.has(i.itemPath),
      ),
    [items, selectedFiles, selectedFolders],
  );

  const handleCopySuccess = useCallback(() => {
    clearSelection();
  }, [clearSelection]);

  // ─── Render ───

  return (
    <div className="flex h-full flex-col">
      {/* Header */}
      <div className="border-b border-border bg-card px-6 py-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <h1 className="text-xl font-semibold text-foreground">File Manager</h1>
            <Badge variant={context.provider === 'azure' ? 'info' : 'warning'}>
              {providerLabel}
            </Badge>
          </div>

          <div className="flex items-center gap-2">
            <Button
              variant={selectionMode ? 'default' : 'outline'}
              size="sm"
              onClick={toggleSelectionMode}
              className="gap-1.5"
            >
              <CheckSquare className="h-4 w-4" />
              {selectionMode ? 'Exit Selection' : 'Select'}
            </Button>

            <Button variant="outline" size="sm" onClick={handleRefresh} className="gap-1.5">
              <RotateCcw className="h-4 w-4" />
              Refresh
            </Button>
          </div>
        </div>

        {/* Breadcrumbs */}
        {breadcrumbs.length > 0 && (
          <nav className="mt-3 flex items-center gap-1 text-sm">
            <button
              onClick={() => handleBreadcrumbClick('')}
              className="text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
            >
              Root
            </button>
            {breadcrumbs.map((crumb, idx) => (
              <span key={idx} className="flex items-center gap-1">
                <ChevronRight className="h-3.5 w-3.5 text-muted-foreground/50" />
                {idx === breadcrumbs.length - 1 ? (
                  <span className="font-medium text-foreground">{crumb.label}</span>
                ) : (
                  <button
                    onClick={() => handleBreadcrumbClick(crumb.path)}
                    className="text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
                  >
                    {crumb.label}
                  </button>
                )}
              </span>
            ))}
          </nav>
        )}
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto p-6">
        {/* Loading */}
        {isLoading && (
          <div className="flex flex-col items-center justify-center gap-3 py-24">
            <Spinner size={28} />
            <p className="text-sm text-muted-foreground">Loading files...</p>
          </div>
        )}

        {/* Error */}
        {!isLoading && error && (
          <div className="flex flex-col items-center justify-center gap-4 py-24">
            <div className="flex h-14 w-14 items-center justify-center rounded-full bg-destructive/10">
              <AlertCircle className="h-7 w-7 text-destructive" />
            </div>
            <div className="text-center">
              <p className="font-medium text-foreground">Failed to load files</p>
              <p className="mt-1 text-sm text-muted-foreground">{error}</p>
            </div>
            <Button variant="outline" size="sm" onClick={handleRefresh} className="gap-1.5">
              <RotateCcw className="h-4 w-4" />
              Retry
            </Button>
          </div>
        )}

        {/* Empty state */}
        {!isLoading && !error && items && items.length === 0 && (
          <div className="flex flex-col items-center justify-center gap-3 py-24">
            <div className="flex h-14 w-14 items-center justify-center rounded-full bg-muted">
              <FolderOpen className="h-7 w-7 text-muted-foreground" />
            </div>
            <p className="font-medium text-foreground">No items found</p>
            <p className="text-sm text-muted-foreground">This folder is empty.</p>
          </div>
        )}

        {/* Files and Folders grid */}
        {!isLoading && !error && items && items.length > 0 && (
          <div className="space-y-6">
            {/* Folders */}
            {folders.length > 0 && (
              <div>
                <h2 className="mb-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Folders ({folders.length})
                </h2>
                <div className="grid grid-cols-[repeat(auto-fill,minmax(140px,1fr))] gap-3">
                  {folders.map((folder) => {
                    const isSelected = selectedFolders.has(folder.itemPath);
                    return (
                      <Tooltip key={folder.itemPath}>
                        <TooltipTrigger asChild>
                          <button
                            className={cn(
                              'group relative flex h-[140px] w-full flex-col items-center justify-center gap-2 rounded-lg border bg-card p-3 transition-colors hover:border-indigo-300 hover:bg-indigo-50/50 cursor-pointer',
                              isSelected && 'border-indigo-400 bg-indigo-50 ring-1 ring-indigo-400/30',
                            )}
                            onClick={() => {
                              if (selectionMode) {
                                toggleFolderSelection(folder.itemPath);
                              } else {
                                handleNavigateToFolder(folder.itemPath);
                              }
                            }}
                          >
                            {selectionMode && (
                              <div className="absolute left-2 top-2">
                                <Checkbox
                                  checked={isSelected}
                                  onCheckedChange={() => toggleFolderSelection(folder.itemPath)}
                                  onClick={(e) => e.stopPropagation()}
                                />
                              </div>
                            )}
                            <Folder className="h-10 w-10 text-amber-500" />
                            <span className="w-full truncate text-center text-xs font-medium text-foreground">
                              {folder.itemName}
                            </span>
                          </button>
                        </TooltipTrigger>
                        <TooltipContent>{folder.itemName}</TooltipContent>
                      </Tooltip>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Files */}
            {files.length > 0 && (
              <div>
                <h2 className="mb-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Files ({files.length})
                </h2>
                <div className="grid grid-cols-[repeat(auto-fill,minmax(140px,1fr))] gap-3">
                  {files.map((file) => {
                    const ext = getFileExtension(file.itemName);
                    const badgeColor = getFileTypeBadgeColor(ext);
                    const isSelected = selectedFiles.has(file.itemPath);
                    return (
                      <Tooltip key={file.itemPath}>
                        <TooltipTrigger asChild>
                          <button
                            className={cn(
                              'group relative flex h-[140px] w-full flex-col items-center justify-center gap-2 rounded-lg border bg-card p-3 transition-colors hover:border-indigo-300 hover:bg-indigo-50/50 cursor-pointer',
                              isSelected && 'border-indigo-400 bg-indigo-50 ring-1 ring-indigo-400/30',
                            )}
                            onClick={() => {
                              if (selectionMode) {
                                toggleFileSelection(file.itemPath);
                              } else {
                                handleFileClick(file);
                              }
                            }}
                          >
                            {selectionMode && (
                              <div className="absolute left-2 top-2">
                                <Checkbox
                                  checked={isSelected}
                                  onCheckedChange={() => toggleFileSelection(file.itemPath)}
                                  onClick={(e) => e.stopPropagation()}
                                />
                              </div>
                            )}
                            <div className="relative">
                              <FileText className="h-10 w-10 text-slate-400" />
                              {ext && (
                                <span
                                  className={cn(
                                    'absolute -bottom-1 -right-2 rounded px-1 py-0.5 text-[10px] font-bold uppercase leading-none',
                                    badgeColor,
                                  )}
                                >
                                  {ext}
                                </span>
                              )}
                            </div>
                            <span className="w-full truncate text-center text-xs font-medium text-foreground">
                              {file.itemName}
                            </span>
                            {file.contentLength != null && (
                              <span className="text-[10px] text-muted-foreground">
                                {formatFileSize(file.contentLength)}
                              </span>
                            )}
                          </button>
                        </TooltipTrigger>
                        <TooltipContent>{file.itemName}</TooltipContent>
                      </Tooltip>
                    );
                  })}
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Detail Sheet */}
      <FileDetailSheet
        open={showDetail}
        onClose={handleCloseDetail}
        file={currentFile ? {
          name: currentFile.itemName,
          path: currentFile.itemPath,
          size: currentFile.contentLength,
          lastModified: currentFile.lastModified,
          contentType: currentFile.contentType,
          metadata: currentFile.metadata,
          downloadUrl: context.account && context.container
            ? `azure/files/item?account=${encodeURIComponent(context.account)}&container=${encodeURIComponent(context.container)}&path=${encodeURIComponent(currentFile.itemPath)}`
            : undefined,
        } : null}
      />

      {/* Copy Dialogs */}
      <CopyToDropboxDialog
        open={activeDialog === 'dropbox'}
        onOpenChange={(o) => !o && setActiveDialog(null)}
        selectedFiles={selectedFileObjects}
        accountName={context.account ?? ''}
        containerName={context.container ?? ''}
        onSuccess={handleCopySuccess}
      />
      <CopyToGoogleDriveDialog
        open={activeDialog === 'google-drive'}
        onOpenChange={(o) => !o && setActiveDialog(null)}
        selectedFiles={selectedFileObjects}
        accountName={context.account ?? ''}
        containerName={context.container ?? ''}
        onSuccess={handleCopySuccess}
      />
      <CopyToGcsDialog
        open={activeDialog === 'gcs'}
        onOpenChange={(o) => !o && setActiveDialog(null)}
        selectedFiles={selectedFileObjects}
        accountName={context.account ?? ''}
        containerName={context.container ?? ''}
        onSuccess={handleCopySuccess}
      />
      <CopyToGooglePhotosDialog
        open={activeDialog === 'google-photos'}
        onOpenChange={(o) => !o && setActiveDialog(null)}
        selectedFiles={selectedFileObjects}
        accountName={context.account ?? ''}
        containerName={context.container ?? ''}
        onSuccess={handleCopySuccess}
      />
      <CopyToPcloudDialog
        open={activeDialog === 'pcloud'}
        onOpenChange={(o) => !o && setActiveDialog(null)}
        selectedFiles={selectedFileObjects}
        accountName={context.account ?? ''}
        containerName={context.container ?? ''}
        onSuccess={handleCopySuccess}
      />

      {/* Bottom Selection Bar */}
      {selectionMode && totalSelected > 0 && (
        <CopyToBar
          sourceProvider="azure"
          selectedCount={totalSelected}
          selectedLabel={formatSelectionCount(selectedFiles.size, selectedFolders.size)}
          onClearSelection={clearSelection}
          onCopyTo={(dest) => setActiveDialog(dest)}
        />
      )}
    </div>
  );
}

// Web.UI/src/app/views/file-manager/file-manager-page/file-manager-page.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Store } from '@ngrx/store';
import { Observable } from 'rxjs';
import { MatDrawer } from '@angular/material/sidenav';
import { MatDialog } from '@angular/material/dialog';
import { FileItem } from '../model/FileItem';
import { FileDetail } from '../model/FileDetail';
import { StorageContext } from '../service/file-manager.service';
import { loadFile, loadFolder, setContext } from '../store/file-manager.actions';
import { getCurrentPath, getFiles, getFolders, getCurrentFile, getShowDetail, getContext, getError, getIsLoading } from '../store/file-manager.selectors';
import { StorageHelpDialogComponent } from '../../storage-browser/storage-help-dialog.component';
import { MigrateDialogComponent, MigrateDialogData } from '../migrate-dialog/migrate-dialog.component';

@Component({
    standalone: false,
    selector: 'app-file-manager-page',
    templateUrl: './file-manager-page.component.html',
    styleUrls: ['./file-manager-page.component.scss']
})
export class FileManagerPageComponent implements OnInit {
    @ViewChild('matDrawer', { static: true }) matDrawer: MatDrawer;
    drawerMode: 'side' | 'over' = 'side';

    files$: Observable<FileItem[]>;
    folders$: Observable<FileItem[]>;
    currentPath$: Observable<string[]>;
    currentFile$: Observable<FileDetail | null>;
    showDetail$: Observable<boolean>;
    context$: Observable<StorageContext>;
    error$: Observable<string | null>;
    isLoading$: Observable<boolean>;
    currentFileItem: FileItem;
    storageBrowserPath: { label: string; level: string }[] = [];
    selectionMode = false;
    selectedFiles = new Set<FileItem>();
    selectedFolders = new Set<FileItem>();
    private currentContext: StorageContext;

    constructor(
        private store: Store,
        private route: ActivatedRoute,
        private router: Router,
        private dialog: MatDialog
    ) {}

    ngOnInit(): void {
        const params = this.route.snapshot.queryParams;
        const provider = (params['provider'] as 'azure' | 'google') || 'azure';
        
        // Redirect to storage browser if account or container is missing
        if (!params['account'] || !params['container']) {
            this.router.navigate(['/storage-browser']);
            return;
        }
        
        const context: StorageContext = {
            provider,
            account: params['account'],
            container: params['container']
        };
        this.currentContext = context;
        this.store.dispatch(setContext({ context }));
        this.loadStorageBrowserPath(context);

        const savedPath = this.getSavedFolderPath(context);
        this.saveFileManagerState(savedPath);
        this.store.dispatch(loadFolder({ path: savedPath }));
        this.files$ = this.store.select(getFiles);
        this.folders$ = this.store.select(getFolders);
        this.currentPath$ = this.store.select(getCurrentPath);
        this.showDetail$ = this.store.select(getShowDetail);
        this.currentFile$ = this.store.select(getCurrentFile);
        this.context$ = this.store.select(getContext);
        this.error$ = this.store.select(getError);
        this.isLoading$ = this.store.select(getIsLoading);
    }

    getFolder(path?: string) {
        this.clearSelection();
        const folderPath = path || null;
        this.saveFileManagerState(folderPath);
        this.store.dispatch(loadFolder({ path: folderPath }));
    }

    getFolderByIndex(currentPath: string[], index: number) {
        let path = currentPath[0];
        for (let i = 1; i < index + 1; i++) {
            path = path + '/' + currentPath[i];
        }
        path = path + '/';
        this.saveFileManagerState(path);
        this.store.dispatch(loadFolder({ path }));
    }

    getFile(item: FileItem) {
        this.store.dispatch(loadFile({ path: item.itemPath }));
        this.currentFileItem = item;
    }

    navigateToStorageBrowser(level: string): void {
        if (level === 'root') {
            sessionStorage.removeItem('storageBrowserState');
        } else {
            const raw = sessionStorage.getItem('storageBrowserState');
            if (raw) {
                const state = JSON.parse(raw);
                delete state.selectedContainer;
                if (level === 'subscriptions') {
                    state.currentLevel = 'resourceGroups';
                } else if (level === 'resourceGroups') {
                    state.currentLevel = 'storageAccounts';
                } else {
                    state.currentLevel = 'containers';
                }
                sessionStorage.setItem('storageBrowserState', JSON.stringify(state));
            }
        }
        this.router.navigate(['/storage-browser']);
    }

    openHelp(): void {
        this.dialog.open(StorageHelpDialogComponent, { width: '560px' });
    }

    toggleSelectionMode(): void {
        this.selectionMode = !this.selectionMode;
        if (!this.selectionMode) {
            this.clearSelection();
        }
    }

    toggleFileSelection(file: FileItem, event: Event): void {
        event.stopPropagation();
        if (this.selectedFiles.has(file)) {
            this.selectedFiles.delete(file);
        } else {
            this.selectedFiles.add(file);
        }
    }

    toggleFolderSelection(folder: FileItem, event: Event): void {
        event.stopPropagation();
        if (this.selectedFolders.has(folder)) {
            this.selectedFolders.delete(folder);
        } else {
            this.selectedFolders.add(folder);
        }
    }

    clearSelection(): void {
        this.selectedFiles.clear();
        this.selectedFolders.clear();
        this.selectionMode = false;
    }

    get hasSelection(): boolean {
        return this.selectedFiles.size > 0 || this.selectedFolders.size > 0;
    }

    openMigrateDialog(): void {
        const data: MigrateDialogData = {
            selectedFiles: Array.from(this.selectedFiles),
            selectedFolders: Array.from(this.selectedFolders),
            account: this.currentContext.account,
            container: this.currentContext.container
        };
        const dialogRef = this.dialog.open(MigrateDialogComponent, {
            width: '520px',
            data
        });
        dialogRef.afterClosed().subscribe(() => {
            this.clearSelection();
        });
    }

    private saveFileManagerState(folderPath: string | null): void {
        sessionStorage.setItem('fileManagerState', JSON.stringify({
            provider: this.currentContext.provider,
            account: this.currentContext.account,
            container: this.currentContext.container,
            folderPath: folderPath
        }));
    }

    private getSavedFolderPath(context: StorageContext): string | null {
        const raw = sessionStorage.getItem('fileManagerState');
        if (!raw) return null;
        try {
            const state = JSON.parse(raw);
            if (state.provider === context.provider &&
                state.account === context.account &&
                state.container === context.container) {
                return state.folderPath || null;
            }
        } catch { /* ignore */ }
        return null;
    }

    private loadStorageBrowserPath(context: StorageContext): void {
        const raw = sessionStorage.getItem('storageBrowserState');
        if (!raw) return;
        try {
            const state = JSON.parse(raw);
            const path: { label: string; level: string }[] = [];
            if (state.selectedSubscription) {
                path.push({ label: state.selectedSubscription.displayName, level: 'subscriptions' });
            }
            if (state.selectedResourceGroup) {
                path.push({ label: state.selectedResourceGroup.name, level: 'resourceGroups' });
            }
            if (state.selectedStorageAccount) {
                path.push({ label: state.selectedStorageAccount.name, level: 'storageAccounts' });
            }
            if (context.container) {
                path.push({ label: context.container, level: 'containers' });
            }
            this.storageBrowserPath = path;
        } catch {
            // ignore malformed state
        }
    }
}

<div class="flex flex-col h-full min-w-0 overflow-hidden">

    <!-- Loading state (before any data arrives) -->
    <div *ngIf="isLoading$ | async" class="flex flex-col flex-auto items-center justify-center gap-4">
        <mat-spinner diameter="44" strokeWidth="4"></mat-spinner>
        <p class="text-sm font-medium text-secondary">Loading files...</p>
    </div>

    <ng-container *ngIf="(isLoading$ | async) === false">
    <ng-container *ngIf="folders$ | async as folders">
    <mat-drawer-container
        class="flex-auto h-full bg-card" *ngIf="files$ | async as files">
        <!-- Drawer -->
        <mat-drawer
            class="w-full sm:w-96"
            [mode]="drawerMode"
            [opened]="showDetail$|async"
            [position]="'end'"
            [disableClose]="true"
            #matDrawer>
            <app-file-detail [file]="currentFile$ | async" [fileItem]="currentFileItem"></app-file-detail>
        </mat-drawer>

        <mat-drawer-content class="flex flex-col">

            <!-- Main -->
            <div class="flex flex-col flex-auto">

                <!-- Storage hierarchy breadcrumbs -->
                <nav class="flex items-center px-6 md:px-8 pt-4 text-sm" *ngIf="storageBrowserPath.length > 0">
                    <button mat-button class="px-2 min-w-0" (click)="navigateToStorageBrowser('root')">
                        <mat-icon class="mr-1" class="!text-[18px] !w-[18px] !h-[18px]">storage</mat-icon>
                        Storage Browser
                    </button>
                    <ng-container *ngFor="let crumb of storageBrowserPath; let last = last">
                        <mat-icon class="text-gray-300 !text-[18px] !w-[18px] !h-[18px]">chevron_right</mat-icon>
                        <button mat-button class="px-2 min-w-0" [disabled]="last" (click)="navigateToStorageBrowser(crumb.level)">
                            {{crumb.label}}
                        </button>
                    </ng-container>
                </nav>

                <!-- Header -->
                <div class="flex flex-col sm:flex-row items-start sm:items-center sm:justify-between p-6 sm:py-8 md:px-8 border-b bg-card">
                    <!-- Title -->
                    <div>
                        <div class="flex items-center gap-3">
                            <div class="text-3xl font-bold tracking-tight leading-none">File Manager</div>
                            <ng-container *ngIf="context$ | async as ctx">
                                <span class="px-2 py-0.5 rounded text-xs font-semibold uppercase"
                                    [ngClass]="{'bg-blue-100 text-blue-800': ctx.provider === 'azure', 'bg-amber-100 text-amber-800': ctx.provider === 'google'}">
                                    {{ctx.provider}}
                                </span>
                                <span *ngIf="ctx.container" class="text-sm text-secondary">
                                    {{ctx.account}} / {{ctx.container}}
                                </span>
                            </ng-container>
                            <div class="ml-auto flex items-center gap-1">
                                <button mat-icon-button class="header-btn"
                                        (click)="toggleSelectionMode()"
                                        [matTooltip]="selectionMode ? 'Exit selection' : 'Select for migration'"
                                        [class.active]="selectionMode">
                                    <mat-icon>{{selectionMode ? 'check_box' : 'check_box_outline_blank'}}</mat-icon>
                                </button>
                                <button mat-icon-button class="header-btn" (click)="openHelp()" matTooltip="Help">
                                    <mat-icon>help_outline</mat-icon>
                                </button>
                            </div>
                        </div>
                        <div class="flex items-center mt-1 font-medium text-secondary">
                            <div class="mr-8" *ngIf="(error$ | async) === null">{{folders.length}} folders, {{files.length}} files</div>
                            <ng-container *ngIf="currentPath$ | async as currentPath">
                                <div class="flex items-center space-x-2" *ngIf="currentPath.length">
                                    <a
                                        class="text-primary cursor-pointer"
                                        (click)="getFolder();">Home
                                    </a>
                                    <div>/</div>
                                    <ng-container *ngFor="let path of currentPath; index as i; let last = last;">
                                        <ng-container *ngIf="!last">
                                            <a
                                                class="text-primary cursor-pointer"
                                                (click)="getFolderByIndex(currentPath, i);">{{path}}</a>
                                        </ng-container>
                                        <ng-container *ngIf="last">
                                            <div>{{path}}</div>
                                        </ng-container>
                                        <ng-container *ngIf="!last">
                                            <div>/</div>
                                        </ng-container>
                                    </ng-container>
                                </div>
                            </ng-container>
                        </div>
                    </div>
                </div>

                <!-- Error -->
                <div *ngIf="error$ | async as error" class="mx-6 md:mx-8 mt-4 p-4 rounded-xl flex items-center gap-3 bg-red-50 border border-red-200">
                    <mat-icon class="text-red-600 !text-[20px] !w-5 !h-5">error_outline</mat-icon>
                    <span class="flex-1 text-sm text-red-800">{{error}}</span>
                    <button mat-icon-button (click)="getFolder()" matTooltip="Retry">
                        <mat-icon>refresh</mat-icon>
                    </button>
                    <button mat-button color="primary" class="text-sm" (click)="openHelp()">
                        <mat-icon class="mr-1" class="!text-base !w-4 !h-4">help_outline</mat-icon>
                        Learn more
                    </button>
                </div>

                <!-- Items list -->
                <ng-container *ngIf="(folders.length > 0 || files.length > 0); else noItems">
                    <div class="p-6 md:p-8 space-y-8" [class.pb-24]="hasSelection">
                        <!-- Folders -->
                        <ng-container *ngIf="folders.length > 0">
                            <div>
                                <div class="font-medium">Folders</div>
                                <div class="flex flex-wrap -m-2 mt-2">
                                    <ng-container *ngFor="let folder of folders;">
                                        <div class="relative w-40 h-40 m-2 p-4 shadow-sm rounded-2xl bg-card border border-gray-100 transition-all hover:shadow-md"
                                             [class.ring-2]="selectedFolders.has(folder)"
                                             [class.ring-primary]="selectedFolders.has(folder)">
                                            <!-- Selection checkbox -->
                                            <div class="absolute top-2 left-2 z-20" *ngIf="selectionMode"
                                                 (click)="toggleFolderSelection(folder, $event)">
                                                <mat-icon class="cursor-pointer text-gray-400 hover:text-primary"
                                                          [class.text-primary]="selectedFolders.has(folder)"
                                                          [class.text-gray-400]="!selectedFolders.has(folder)">
                                                    {{selectedFolders.has(folder) ? 'check_box' : 'check_box_outline_blank'}}
                                                </mat-icon>
                                            </div>
                                            <a class="z-10 absolute inset-0 flex flex-col p-4 cursor-pointer"
                                               (click)="selectionMode ? toggleFolderSelection(folder, $event) : getFolder(folder.itemPath)">
                                                <div class="flex items-center justify-center flex-1">
                                                    <mat-icon class="text-6xl text-hint" style="font-size: 56px; width: 56px; height: 56px;">folder</mat-icon>
                                                </div>
                                                <div class="flex flex-col flex-auto justify-center text-center text-sm font-medium">
                                                    <div
                                                        class="truncate"
                                                        [matTooltip]="folder.itemPath">{{folder.itemName}}</div>
                                                </div>
                                            </a>
                                        </div>
                                    </ng-container>
                                </div>
                            </div>
                        </ng-container>

                        <!-- Files -->
                        <ng-container *ngIf="files.length > 0">
                            <div>
                                <div class="font-medium">Files</div>
                                <div class="flex flex-wrap -m-2 mt-2">
                                    <ng-container *ngFor="let file of files;">
                                        <div class="relative flex flex-col w-40 h-40 m-2 p-4 shadow-sm rounded-2xl bg-card border border-gray-100 cursor-pointer transition-all hover:shadow-md"
                                             [class.ring-2]="selectedFiles.has(file)"
                                             [class.ring-primary]="selectedFiles.has(file)"
                                             (click)="selectionMode ? toggleFileSelection(file, $event) : getFile(file)">
                                            <!-- Selection checkbox -->
                                            <div class="absolute top-2 left-2 z-20" *ngIf="selectionMode"
                                                 (click)="toggleFileSelection(file, $event)">
                                                <mat-icon class="cursor-pointer hover:text-primary"
                                                          [class.text-primary]="selectedFiles.has(file)"
                                                          [class.text-gray-400]="!selectedFiles.has(file)">
                                                    {{selectedFiles.has(file) ? 'check_box' : 'check_box_outline_blank'}}
                                                </mat-icon>
                                            </div>
                                            <div class="flex items-center justify-center flex-1">
                                                <div class="relative">
                                                    <mat-icon class="text-6xl text-hint" style="font-size: 56px; width: 56px; height: 56px;">description</mat-icon>
                                                    <div
                                                        class="absolute left-0 bottom-0 px-1.5 rounded text-sm font-semibold leading-5 text-white"
                                                        [ngClass]="{
                                                            'bg-red-600': file.itemType === 'PDF',
                                                            'bg-blue-600': file.itemType === 'DOC',
                                                            'bg-green-600': file.itemType === 'XLS',
                                                            'bg-gray-600': file.itemType === 'TXT',
                                                            'bg-amber-600': file.itemType === 'JPG' || file.itemType === 'JPEG',
                                                            'bg-teal-600': file.itemType !== 'PDF' && file.itemType !== 'DOC' && file.itemType !== 'XLS' && file.itemType !== 'TXT' && file.itemType !== 'JPG' && file.itemType !== 'JPEG'
                                                        }">
                                                        {{file.itemType}}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="flex flex-col flex-auto justify-center text-center text-sm font-medium">
                                                <div
                                                    class="truncate"
                                                    [matTooltip]="file.itemName">{{file.itemName}}</div>
                                            </div>
                                        </div>
                                    </ng-container>
                                </div>
                            </div>
                        </ng-container>
                    </div>
                </ng-container>

                <!-- No items template -->
                <ng-template #noItems>
                    <div *ngIf="(error$ | async) === null" class="flex flex-auto flex-col items-center justify-center">
                        <mat-icon class="!text-[80px] !w-20 !h-20 text-black/15">folder_open</mat-icon>
                        <div class="mt-4 text-xl font-semibold tracking-tight text-secondary">No items found</div>
                        <div class="mt-2 text-sm text-secondary">This folder is empty.</div>
                    </div>
                </ng-template>

            </div>

        </mat-drawer-content>

    </mat-drawer-container>
    </ng-container>
    </ng-container>

    <!-- Selection action bar -->
    <div *ngIf="hasSelection"
         class="fixed bottom-0 left-0 right-0 z-50 flex items-center justify-between px-8 py-3 bg-white border-t shadow-lg">
        <div class="text-sm font-medium">
            <span *ngIf="selectedFiles.size > 0">{{selectedFiles.size}} file{{selectedFiles.size !== 1 ? 's' : ''}}</span>
            <span *ngIf="selectedFiles.size > 0 && selectedFolders.size > 0"> and </span>
            <span *ngIf="selectedFolders.size > 0">{{selectedFolders.size}} folder{{selectedFolders.size !== 1 ? 's' : ''}}</span>
            selected
        </div>
        <div class="flex items-center gap-3">
            <button mat-button (click)="clearSelection()">Clear</button>
            <button mat-flat-button color="primary" (click)="openMigrateDialog()">
                <mat-icon class="mr-1">cloud_upload</mat-icon>
                Migrate to Google Photos
            </button>
            <button mat-flat-button class="btn-gcs" (click)="openCopyToGcsDialog()">
                <mat-icon class="mr-1">cloud_upload</mat-icon>
                Copy to GCS
            </button>
        </div>
    </div>

</div>
